name: PR Precheck

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  Precheck:
    name: Precheck
    runs-on: ubuntu-latest
    env:

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint Check
        run: npm run lint

      - name: Build Check
        run: npm run build
